---
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
server:
  port: 8080
spring:
  application:
    name: eureka-client
  security:
    user:
      name: zcy
      password: zcy
  profiles: 8080

---
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
server:
  port: 8081
spring:
  application:
    name: eureka-client
  security:
    user:
      name: zcy
      password: zcy
  profiles: 8081
