eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: eureka-client
  security:
    user:
      name: zcy
      password: zcy
