---
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    # 默认情况下，eureka会像自己注册，将下面两个属性设置为false
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${eureka.instance.hostname}:${server.port}/eureka-server/
spring:
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: zcy
      password: zcy

---
server:
  port: 8762

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${eureka.instance.hostname}:${server.port}/eureka-server/

spring:
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: zcy
      password: zcy
