spring:
  application:
    name: cloud-study
  zipkin:
    # zipkin服务端地址，即将调用信息上传到什么地方
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 以100%的概率将调用链路数据上传给zipkin server
      percentange: 1.0
server:
  port: 8764
  servlet:
    context-path: /cloud-study
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


